### ISSUE TITLE
Distinguish SNOMED Versions

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/OMOP-Standardized-Vocabularies#10]
An improvement to the vocabularies would be to distinguish the different country versions of SNOMED. If a code is from the British version of SNOMED, the vocabulary_name = SNOMED UK. Or something of the sort. This would be very useful in mapping local source codes. It would also make the lookup of codes in the SNOMED browser easier since you need to specify which country version you want to search for a code.

**Comment by dimshitc** [comment]
@cgreich , what do you think?

**Comment by cgreich** [comment]
@MelaniePhilofsky:

Can you get into your time machine and make this proposal like in 2009 or so? :) Now it would be a big fat mess. We could do it, but do you have a strong enough use case for us to justify an open heart surgery like that?

**Comment by dimshitc** [comment]
yeah, 
we need to deprecate all these SNOMED UK (marked as SNOMED now) and yes, it makes a mess now.

Can we change the concepts_class_id for these UK concepts?
Will it make sense?

**Comment by MelaniePhilofsky** [comment]
@cgreich ,

I am withdrawing my proposal. I don't think open heart surgery is necessary. I'll just post to the forum when I get lost in the multiple versions of SNOMED.

Thanks,
Melanie
