### ISSUE TITLE
plasme typo in lab concept name - instead of plasma

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/OMOP-Standardized-Vocabularies#11]
Thanks to Themis study - I saw a typo in concept name 
here:
http://www.ohdsi.org/web/atlas/#/concept/3001784

![image](https://user-images.githubusercontent.com/7526119/35114825-309c0620-fc54-11e7-88af-3b40f170e924.png)

it is LOINC concept of 
https://r.details.loinc.org/LOINC/12841-3.html?sections=Comprehensive

the LOINC name does not have this typo.

![image](https://user-images.githubusercontent.com/7526119/35114934-7b78f874-fc54-11e7-86d6-86dd474c23a3.png)

Is there a bug in importing LOINC? How come the typo is in Athena?

**Comment by dimshitc** [comment]
Thanks for reporting. We'll take a look on way of LOINC name extraction and fix this

**Comment by aostropolets** [comment]
closed as a duplicate
