### ISSUE TITLE
SNOMED Concept replaced by but no Maps to relationship

### ISSUE THREAD

**Issue by don-torok** [OHDSI/OMOP-Standardized-Vocabularies#15]
Is this a problem
There is no 'Maps to' releationship for SNOMED concept id 45958972 (Icatibant acetate) which is Replace by concept 45773118 (Icatibant acetate)

I expected a 'Maps to' relationship from 45958972 to 45773118 in addition to the 'Concept replaced by' relationship. Otherwise users must first follow the 'Concept replaced by' for any updated concepts prior to following the 'Maps to' relationship.
	
From the discussion in a prior forum post I was led to believe it was not necessary to first follow the 'Concept replaced by' relationship prior to looking for the standard, 'Maps to', concept.
	
Note: looking at another example, Concept id 3034863 for LOINC code 35719-4, I do see both a 'Maps to' and 'Concept replaced by' relationship.

**Comment by aostropolets** [comment]
'Maps to' relationship connects standard and non-standard concepts, which is not the case here (45773118  is non-standard). Then you can see 'SNOMED - RxNorm eq' from 45773118 to 46274266 
(RxNorm) icatibant acetate.
From the discussion in a prior forum post I was led to believe it was not necessary to first follow the 'Concept replaced by' relationship prior to looking for the standard, 'Maps to', concept.
<<< absolutely true when you do have 'Maps to' relationship. Here you need to follow white 'SNOMED - RxNorm eq' rabbit.

**Comment by guanguounsw** [comment]
We are looking at using some race concepts in Australian context and came across 4030302 (South Asian AND/OR Australian aborigine) it's a non-standard concept, it does not have "replaced by" or  "maps to".

**Comment by dimshitc** [comment]
Hi @guanguounsw , 
we use this list of concepts to define a Race
https://www.cdc.gov/nchs/data/dvs/Race_Ethnicity_CodeSet.pdf
Can 38003613 "Other Pacific Islander" concept be used instead?
