### ISSUE TITLE
Missing Historic CPT Codes

### ISSUE THREAD

**Issue by djb2188** [OHDSI/OMOP-Standardized-Vocabularies#18]
Please see the attached file. With the current OHDSI vocabulary, historic CPT codes remain sparsely populated. We scrubbed our missing CPT codes with an IDX/Billing System/Procedure dictionary and populated the attached file. We hope this file can help the OHDSI vocabulary team backfill some of the historic gaps.

*Please note the query used to generate the attached file used an OHDSI databased that had CPT Version C2017AA loaded.

Many thanks!

David Blatt
 
[MissingCU_CPT_2017AA.xlsx](https://github.com/OHDSI/OMOP-Standardized-Vocabularies/files/1916751/MissingCU_CPT_2017AA.xlsx)

**Comment by cgreich** [comment]
@djb2188: Looks like that's a mixture of CPT4 and HCPCS. Correct?

**Comment by djb2188** [comment]
@cgreich  Yes, that is a good point. Perhaps some of these are HCPCS level 2,3 etc. Source designates them all as CPT. Is it possible that the HCPCS level 1 component of the Vocabulary has a deeper history then the version of CPT in the vocabulary?  Pondering.....

**Comment by cgreich** [comment]
@djb2188: Doesn't matter. We'll add.

**Comment by cukarthik** [comment]
hey @cgreich were some of these codes added. just checking. thanks.

**Comment by djb2188** [comment]
[CU_NYP_CPT-HCPCS_GAPS.txt](https://github.com/OHDSI/OMOP-Standardized-Vocabularies/files/2290400/CU_NYP_CPT-HCPCS_GAPS.txt)

@cgreich here is an updated file.

**Comment by cgreich** [comment]
Thanks, @djb2188.
