### ISSUE TITLE
ATC5th - add synonyms with path

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/OMOP-Standardized-Vocabularies#26]
an isolated atc5 name is hard to interpret.

having some mechanism (e.g., path to it as synonym) to see that would be good.

**Comment by cgreich** [comment]
@vojtechhuser: Good idea, except not clear how to do it. We could trying clipping some part of the ATC4 or 3 off, that characterizes the ATC5 a little better. Will bring it up with the WHO.

**Comment by aostropolets** [comment]
Actually, when Vojtech brought it up today I thought of combining the path of an ATH5th in its synonym name (e.g. ATC 2nd - ATC 3rd -ATC4th - ATC 5th). I need to think of the way to make those synonyms look nice
