### ISSUE TITLE
v5.0 12-FEB-16

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/OMOP-Standardized-Vocabularies#3]
Is this the newest release?

**Comment by cgreich** [comment]
Yes, but wait till end of the week.

**Comment by vojtechhuser** [comment]
If possible, please do update this github once there is a new release. (for those of us waiting on the icd10cm inclusion)

**Comment by cgreich** [comment]
Yes. It's ready to go. We have trouble with a new release with something that is unrelated to this. Working feverishly.

**Comment by cgreich** [comment]
Done.
