### ISSUE TITLE
Zoster Vaccine - CVX 187

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/OMOP-Standardized-Vocabularies#31]
Hi,

The code CVX 187 for the Zoster vaccine doesn't seem to be available in our vocabulary. Would it be possible to add it?

Many thanks,

**Comment by dimshitc** [comment]
Hi, yes, we need to update CVX, we'll do it this week.

**Comment by dimshitc** [comment]
Done. CVX is updated
