### ISSUE TITLE
CPT to CVX Mappings

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/OMOP-Standardized-Vocabularies#32]
There seems to be a mismatch with the mapping of the following vaccines:

Hepatitis B vaccines:
CPT 90739 should map to CVX 189
CPT 90743 should map to CVX 43
CPT 90740 should map to CVX 44

Zoster vaccines:
CPT 90750 should map to CVX 187
CPT 90736 should map to CVX 121

Meningococcal B vaccines:
CPT 90620 should map to CVX 163
CPT 90621 should map to CVX 162

Influenza vaccines:
90653 should map to 168
90654 should map to 144
90655 should map to 140
90656 should map to 140
90657 should map to 141
90658 should map to 141
90661 should map to 153
90662 should map to 135
90664 should map to 125
90666 should map to 126
90668 should map to 127
90673 should map to 155
90674 should map to 171
90682 should map to 185
90685 should map to 161
90686 should map to 150
90687 should map to 158
90688 should map to 158

*Source: https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww2a.cdc.gov%2Fvaccines%2Fiis%2Fiisstandards%2Fvaccines.asp%3Frpt%3Dcpt&amp;data=02%7C01%7Csfowler%40us.imshealth.com%7C09f45810f29c42c28e8d08d692bc6204%7C5989ece0f90e40bf9c791a7beccdb861%7C1%7C0%7C636857735176220485&amp;sdata=zXNnyOJH7DWEru9v3NfphVeEETu7j4zN%2FXcb7hd6mss%3D&amp;reserved=0

I would be very grateful if you could consider the above issues and suggest a timeline for when do you expect this could be reviewed.

**Comment by dimshitc** [comment]
Thanks, looks like a nice source. So, after the CVX update we'll add these crosswalks to OMOP vocabulary. Hope, we'll be able to finish it this week.

**Comment by dimshitc** [comment]
Done. These mappings are available on Athena
