### ISSUE TITLE
MeSH-to-standard concept mapping

### ISSUE THREAD

**Issue by kp14** [OHDSI/OMOP-Standardized-Vocabularies#39]
Hi,

In Athena, the MeSH concept 'Zika Virus Infection' (concept ID 28543) is listed as mapping to the the standard concept ID 4214984 in the section 'term connections' ([see here](http://athena.ohdsi.org/search-terms/terms/28543)). Based on this, when I downloaded the MeSH vocabulary data from Athena, I expected to find a 'Maps to' relationship from 28543 -> 4214984 in the file CONCEPT_RELATIONSHIP.csv. It is not there though. 

Is there a way to explore mappings of the non-standard MeSH concepts to the standard concepts apart from looking at individual terms in Athena? 

Note: 
I have only just started exploring Athena so it might well be that I am not seeing the obvious or lack understanding of the OMOP mappings.

Any pointers you might be able to give will be greatly appreciated.

Regards,
Klemens

**Comment by dimshitc** [comment]
Did you include both MeSH and Snomed in a bunch? There are checkboxes near
the vocabulary names.

**Comment by kp14** [comment]
No, I downloaded them separately. Aha, so the preparation process that takes place before a download is ready takes care of linking the selected vocabularies? I will try that. Thanks for the hint!

**Comment by kp14** [comment]
Yes, that was it. Now I have the expected mapping.

Thank you very much for your help!
