### ISSUE TITLE
Death Type for Different Source

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/OMOP-Standardized-Vocabularies#4]
Should there be another concept type id for death information from the social security death index file?

**Comment by cgreich** [comment]
Not sure, karthiksmith. The Death Type is not pointing to a specific named source or vocabulary. Rather, it describes the logical source of the information. If you get data from the Death Index that is from Death Certificates, if I am not mistaken. Is that true?

**Comment by karthiksmith** [comment]
That's what I had initially thought, but I don't think we can make that assumption - https://www.ssa.gov/dataexchange/request_dmf.html. The death data is an aggregation of death information that is received from various death reports from many sources, including family members, funeral homes, financial institutions, postal authorities, States and other Federal agencies. 
I wonder if it makes sense to create an additional death type that is something like "Gov't reported/identified death". What do you think?

**Comment by cgreich** [comment]
Makes sense. Will put it in.

**Comment by cgreich** [comment]
Done
