### ISSUE TITLE
Vocabulary Domain Misclassified

### ISSUE THREAD

**Issue by noahgengel** [OHDSI/OMOP-Standardized-Vocabularies#43]
Hello,

After some investigation, Zoey and I (both from CUMC) an OMOP concept classified under the wrong domain:

4150977: Electron spin resonance measurement 

The above is in the 'procedure' domain and should be placed in the 'measurement' domain.

Please let either of us know if you have any further questions,
Noah Engel

**Comment by cgreich** [comment]
A Measurement is a "structured values (numerical or categorical) obtained through systematic and standardized examination or testing of a Person or Person's sample". Having the word "measurement" in the description doesn't make it one. The electron spin resonance is measured, but the report is an image (not a numerical or categorical value), which gets interpreted for diagnostic purposes. So, it's really a diagnostic procedure, like an endoscopy or angiography.

**Comment by noahgengel** [comment]
That makes sense; thank you for the clarification!
